### ISSUE TITLE
Disqus abschaffen

### ISSUE THREAD

**Issue by screeny05** [shyim/shy.im#5]
Disqus ist in der Vergangenheit öfter negativ aufgefallen:
* https://www.heise.de/security/meldung/Disqus-Hack-17-5-Millionen-Nutzerdaten-im-Umlauf-3852092.html
* http://www.denofgeek.com/us/culture/den-of-geek/265778/were-changing-our-comments-system

Vorschläge für Alternativen:
* Remarkbox
* Selbst gehostete Lösung

**Comment by shyim** [comment]
Ich schau mir das mal an mit Remarkbox :)

**Comment by shyim** [comment]
Hast du ne Idee, wieso das ding ein 502 wirft. Lokal hat der Snippet funktioniert.. hmm..

**Comment by screeny05** [comment]
Nope, keine Ahnung

**Comment by shyim** [comment]
Habs entfernt.. Bis ich irgendein anderes Platform finde

**Comment by Wachert** [comment]
Kann man nicht die Github "Discussion" Funktion dafür in irgendeiner Weise einbinden?

**Comment by shyim** [comment]
Done hab jetzt ein Isso Server aufgesetzt
